# Task 4:
# # Use nginx:alpine as base
# FROM nginx:alpine

# # Copy index.html to the Nginx web directory
# COPY index.html /usr/share/nginx/html/index.html




# Task 5:
# Use nginx:alpine as base
FROM nginx:alpine

# Working dir
WORKDIR /usr/share/nginx/html

# Copy everything from the current Windows directory into the container
COPY . .